### ISSUE TITLE
could you please share the code training the network

### ISSUE THREAD

**Issue by 3DMM-ICME2023** [tianshuichen/Wavelet-like-Auto-Encoder#1]
Thanks for your nice works! @tianshuichen 
I am very interested in your wonderful work. However, I only find the testing code, could you please share the code training the network?

**Comment by tianshuichen** [comment]
We will release the training code when completing the journal version.

**Comment by 3DMM-ICME2023** [comment]
Thanks for your reply! Stay tuned!
